package com.wonders.dao;
		
import java.io.*;
import java.math.*;
import java.sql.*;
import java.text.*;
import javax.persistence.*;
import javax.xml.bind.annotation.adapters.*;
import org.apache.commons.lang.builder.*;
import wfc.facility.tool.autocode.*;
import wfc.service.util.*;

/**
 * 
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "EASYUI_TREE")
public class EasyuiTree implements Serializable {
    
    /**
     * 
     */
    public static final String EASYUI_TREE = "EASYUI_TREE";
    
    /**
     * 
     */
    public static final String ID = "ID";
    
    /**
     * 
     */
    public static final String CHECKED = "CHECKED";
    
    /**
     * 
     */
    public static final String ICONCLS = "ICONCLS";
    
    /**
     * 
     */
    public static final String PARENTID = "PARENTID";
    
    /**
     * 
     */
    public static final String TEXT = "TEXT";
    
    /**
     * 
     */
    public static final String URL = "URL";
    
    /**
     * 
     */
    public static final String LAST_MODIFIED = "LAST_MODIFIED";
    
    public EasyuiTree() {
    }

    /**
     * 
     */
    @Id
    @Column(name = "ID")
    private String id;

    /**
     * 
     */
    @Column(name = "CHECKED")
    private String checked;

    /**
     * 
     */
    @Column(name = "ICONCLS")
    private String iconcls;

    /**
     * 
     */
    @Column(name = "PARENTID")
    private String parentid;

    /**
     * 
     */
    @Column(name = "TEXT")
    private String text;

    /**
     * 
     */
    @Column(name = "URL")
    private String url;

    /**
     * 
     */
    @Column(name = "LAST_MODIFIED")
    private Timestamp lastModified;

	/**
     * 
     */
    public String getId() {
        return this.id;
    }
    
    /**
     * 
     */
    public String id2Html() {
        return StringHelper.replaceHTMLSymbol(this.id);
    }

    /**
     * 
     */
    public void setId(String id) {
        id = AutoCodeConstant.substringBySize(id, 255, false);
        this.id = id;
    }

	/**
     * 
     */
    public String getChecked() {
        return this.checked;
    }
    
    /**
     * 
     */
    public String checked2Html() {
        return StringHelper.replaceHTMLSymbol(this.checked);
    }

    /**
     * 
     */
    public void setChecked(String checked) {
        checked = AutoCodeConstant.substringBySize(checked, 32, false);
        this.checked = checked;
    }

	/**
     * 
     */
    public String getIconcls() {
        return this.iconcls;
    }
    
    /**
     * 
     */
    public String iconcls2Html() {
        return StringHelper.replaceHTMLSymbol(this.iconcls);
    }

    /**
     * 
     */
    public void setIconcls(String iconcls) {
        iconcls = AutoCodeConstant.substringBySize(iconcls, 32, false);
        this.iconcls = iconcls;
    }

	/**
     * 
     */
    public String getParentid() {
        return this.parentid;
    }
    
    /**
     * 
     */
    public String parentid2Html() {
        return StringHelper.replaceHTMLSymbol(this.parentid);
    }

    /**
     * 
     */
    public void setParentid(String parentid) {
        parentid = AutoCodeConstant.substringBySize(parentid, 32, false);
        this.parentid = parentid;
    }

	/**
     * 
     */
    public String getText() {
        return this.text;
    }
    
    /**
     * 
     */
    public String text2Html() {
        return StringHelper.replaceHTMLSymbol(this.text);
    }

    /**
     * 
     */
    public void setText(String text) {
        text = AutoCodeConstant.substringBySize(text, 100, false);
        this.text = text;
    }

	/**
     * 
     */
    public String getUrl() {
        return this.url;
    }
    
    /**
     * 
     */
    public String url2Html() {
        return StringHelper.replaceHTMLSymbol(this.url);
    }

    /**
     * 
     */
    public void setUrl(String url) {
        url = AutoCodeConstant.substringBySize(url, 32, false);
        this.url = url;
    }

	/**
     * 
     */
    @XmlJavaTypeAdapter(TimestampXmlAdapter.class)
    public Timestamp getLastModified() {
        return this.lastModified;
    }
    
    /**
     * 
     */
    public String lastModified2Html(String pattern) {
        if (this.lastModified == null) {
            return "";
        } else {
            if (pattern == null) {
                pattern = "yyyy年MM月dd日 HH时mm分";
            }
            return new SimpleDateFormat(pattern).format(this.lastModified);
        }
    }

    /**
     * 
     */
    public void setLastModified(Timestamp lastModified) {
        
        this.lastModified = lastModified;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

}