package com.wonders.dao;
		
import java.io.*;
import java.math.*;
import java.sql.*;
import java.text.*;
import javax.persistence.*;
import javax.xml.bind.annotation.adapters.*;
import org.apache.commons.lang.builder.*;
import wfc.facility.tool.autocode.*;
import wfc.service.util.*;

/**
 * 
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_PERMISSION")
public class TPermission implements Serializable {
    
    /**
     * 
     */
    public static final String T_PERMISSION = "T_PERMISSION";
    
    /**
     * 
     */
    public static final String ID = "ID";
    
    /**
     * 
     */
    public static final String PERMISSION_NAME = "PERMISSION_NAME";
    
    /**
     * 
     */
    public static final String REMARKS = "REMARKS";
    
    public TPermission() {
    }

    /**
     * 
     */
    @Column(name = "ID")
    @Id
    private BigDecimal id;

    /**
     * 
     */
    @Column(name = "PERMISSION_NAME")
    private String permissionName;

    /**
     * 
     */
    @Column(name = "REMARKS")
    private String remarks;

	/**
     * 
     */
    public BigDecimal getId() {
        return this.id;
    }
    
    /**
     * 
     */
    public String id2Html(int precision) {
        if (this.id == null) {
            return "";
        } else {
            String pattern = "0";
            if (precision > 0) {
                pattern += ".";
                for (int i = 0; i < precision; i++) {
                    pattern += "0";
                }
            }
            return new DecimalFormat(pattern).format(this.id);
        }
    }

    /**
     * 
     */
    public void setId(BigDecimal id) {
        
        this.id = id;
    }

	/**
     * 
     */
    public String getPermissionName() {
        return this.permissionName;
    }
    
    /**
     * 
     */
    public String permissionName2Html() {
        return StringHelper.replaceHTMLSymbol(this.permissionName);
    }

    /**
     * 
     */
    public void setPermissionName(String permissionName) {
        permissionName = AutoCodeConstant.substringBySize(permissionName, 50, false);
        this.permissionName = permissionName;
    }

	/**
     * 
     */
    public String getRemarks() {
        return this.remarks;
    }
    
    /**
     * 
     */
    public String remarks2Html() {
        return StringHelper.replaceHTMLSymbol(this.remarks);
    }

    /**
     * 
     */
    public void setRemarks(String remarks) {
        remarks = AutoCodeConstant.substringBySize(remarks, 1000, false);
        this.remarks = remarks;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

}