package com.wonders.dao;

import java.math.*;
import java.sql.*;
import java.util.*;

import org.springframework.stereotype.Repository;
import wfc.facility.tool.autocode.*;
import wfc.service.database.*;

/**
 * 
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class TUserRoleDao {

    private Connection con = null;

    public TUserRoleDao() {
    }

    public TUserRoleDao(Connection con) {
        this.con = con;
    }

    public void add(TUserRole info) {
        String sql = "insert into T_USER_ROLE(ID, REMARKS, ROLE_ID, USER_ID) values (?, ?, ?, ?)";
        Object[] obj = {
            info.getId(),
            info.getRemarks(),
            info.getRoleId(),
            info.getUserId()
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update T_USER_ROLE set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from T_USER_ROLE";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

    public PaginationArrayList<TUserRole> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("T_USER_ROLE", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "T_USER_ROLE", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<TUserRole> pal = new PaginationArrayList<TUserRole>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            TUserRole info = new TUserRole();
            info.setId(rs.getBigDecimal("ID"));
            info.setRemarks(rs.getOriginalString("REMARKS"));
            info.setRoleId(rs.getBigDecimal("ROLE_ID"));
            info.setUserId(rs.getBigDecimal("USER_ID"));
            pal.add(info);
        }
        return pal;
    }

    public List<TUserRole> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("T_USER_ROLE", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "T_USER_ROLE", "*", conds, suffix);
        }
        ArrayList<TUserRole> al = new ArrayList<TUserRole>();
        while (rs.next()) {
            TUserRole info = new TUserRole();
            info.setId(rs.getBigDecimal("ID"));
            info.setRemarks(rs.getOriginalString("REMARKS"));
            info.setRoleId(rs.getBigDecimal("ROLE_ID"));
            info.setUserId(rs.getBigDecimal("USER_ID"));
            al.add(info);
        }
        return al;
    }

}